name: video_js_player
description: "Video Library for Flutter, Easily use famuse video.js in flutter web"
version: 0.0.6
homepage: https://github.com/emintolgahanpolat/video_js_player

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
