name: video_js_player
description: "Video Library for Flutter, Easily use famuse video.js in flutter web"
version: 0.0.15
homepage: https://github.com/emintolgahanpolat/video_js_player

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  visibility_detector: ^0.4.0+2
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/player/
    - assets/player/videojs/
